// LIVE per-project database — the leap from "ships a schema file" to "the app runs on a real DB".
// Each project's tables live in their OWN Postgres schema `app_<hex>`, NEVER `public`. Every operation
// is namespace-isolated, identifier-validated, and parameterized, so a produced app's data model is real
// and queryable while the engine's tables (public) can never be touched. This is the safety contract:
// the only schema we ever create/drop/write is `app_<32hex>` derived from the project UUID.
import pg from 'pg';
import { parseModel, compile } from './schema.ts';

const IDENT = /^[a-z_][a-z0-9_]*$/;            // a legal, safe SQL identifier (no quoting tricks)

// app_<32 hex of the project uuid>. Throws on anything that wouldn't be exactly this — so we can NEVER
// accidentally operate on `public`, an empty name, or an injected identifier.
export function schemaName(projectId: string): string {
  const hex = String(projectId || '').toLowerCase().replace(/[^a-f0-9]/g, '');
  if (hex.length < 16) throw new Error('appdb: refusing — project id too short to namespace: ' + projectId);
  const name = 'app_' + hex.slice(0, 32);
  if (!/^app_[a-f0-9]{16,32}$/.test(name)) throw new Error('appdb: bad schema name ' + name);
  return name;
}

const stripFences = (s: string) => s.replace(/```[a-zA-Z]*\n?/g, '').replace(/```/g, '').trim();
function sqlBody(content: string): string { const s = stripFences(content); const at = s.search(/create\s+table/i); return at >= 0 ? s.slice(at) : s; }

// Strip SQL comments and normalize whitespace (incl. around dots) so the confinement denylist can't be
// fooled by `public /* */ . foo`, `copy\nfrom`, or `set/**/role`. The SANITIZED text is what we both
// validate AND execute, so what passes the check is exactly what runs.
function sanitizeDdl(content: string): string {
  return sqlBody(content)
    .replace(/\/\*[\s\S]*?\*\//g, ' ')   // /* block comments */
    .replace(/--[^\n]*/g, ' ')           // -- line comments
    .replace(/\s+/g, ' ')                // collapse whitespace/newlines
    .replace(/\s*\.\s*/g, '.')           // "public . foo" / "public/**/.foo" -> "public.foo"
    .trim();
}

// Reject any DDL that could escape the project's schema or touch the engine. Generated app DDL never
// legitimately references another schema or session settings — so blocking these is free safety.
function assertConfined(ddl: string) {
  const lower = ddl.toLowerCase();
  // the engine pool is a superuser, so block anything beyond plain tables/indexes/inserts: cross-schema
  // refs, session settings, procedural/privilege/extension constructs, and IO functions.
  for (const bad of ['public.', 'pg_catalog', 'pg_class', 'information_schema', 'search_path', 'set role',
    'set session', 'create schema', 'drop schema', 'drop database', 'alter system', '\\connect', 'dblink',
    'copy ', 'pg_read', 'pg_sleep', 'create extension', 'create or replace', 'create function',
    'create trigger', 'create policy', 'security definer', 'grant ', 'revoke ', 'alter role', 'alter user'])
    if (lower.includes(bad)) throw new Error('appdb: schema DDL contains a disallowed construct: ' + bad.trim());
}

const SENSITIVE = /pass|secret|token|hash|salt|api_?key|private|credential/i;   // never expose these via the public read API

// Provision the project's schema FOR REAL: drop+recreate its isolated namespace and apply the DDL (+ any
// seed INSERTs) inside it. Idempotent — a rebuild re-provisions cleanly. Returns the tables that now exist.
// The agent's DB output -> final DDL: a JSON data-model is COMPILED into perfect, consistent Postgres
// (PKs, FK indexes, types, defaults); raw SQL falls back to the sanitized+confined path (legacy).
export function compileDDL(content: string): { ddl: string; warnings: string[] } {
  const model = parseModel(content);
  if (model) { const c = compile(model); return { ddl: c.ddl, warnings: c.warnings }; }   // generated by us -> trusted
  const ddl = sanitizeDdl(content); assertConfined(ddl); return { ddl, warnings: [] };       // raw SQL -> confine
}

export async function provision(pool: pg.Pool, projectId: string, content: string): Promise<{ schema: string; tables: string[] }> {
  const schema = schemaName(projectId);
  const { ddl } = compileDDL(content);
  if (!/create\s+table/i.test(ddl)) throw new Error('appdb: no tables in the data model / schema output');
  // IDEMPOTENT + non-destructive: if the project schema is already provisioned, keep its data — never
  // re-drop on a rebuild or a verify retry (that would wipe the live app's records).
  const existing = await listTables(pool, projectId);
  if (existing.length) return { schema, tables: existing };
  const c = await pool.connect();
  try {
    await c.query('begin');
    await c.query("set local statement_timeout = '15s'");           // bound pathological/runaway DDL
    await c.query(`create schema if not exists "${schema}"`);        // never public; safe under concurrency
    await c.query(`set local search_path to "${schema}"`);           // unqualified CREATE/INSERT land HERE; tx-scoped
    await c.query(ddl);
    await c.query('commit');
  } catch (e) { try { await c.query('rollback'); } catch {} throw e; }
  finally { c.release(); }
  return { schema, tables: await listTables(pool, projectId) };
}

export async function listTables(pool: pg.Pool, projectId: string): Promise<string[]> {
  const schema = schemaName(projectId);
  const r = await pool.query(
    "select table_name from information_schema.tables where table_schema=$1 and table_type='BASE TABLE' order by table_name", [schema]);
  return r.rows.map((x: any) => x.table_name);
}

async function columns(pool: pg.Pool, schema: string, table: string): Promise<string[]> {
  const r = await pool.query('select column_name from information_schema.columns where table_schema=$1 and table_name=$2', [schema, table]);
  return r.rows.map((x: any) => x.column_name);
}

// Read rows from a REAL project table (validated against the schema's own catalog; never arbitrary SQL).
export async function readRows(pool: pg.Pool, projectId: string, table: string, limit = 50): Promise<any[]> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table)) return [];
  const tables = await listTables(pool, projectId);
  if (!tables.includes(table)) return [];
  const lim = Math.max(1, Math.min(200, Number(limit) || 50));
  const r = await pool.query(`select * from "${schema}"."${table}" limit ${lim}`);
  return r.rows.map((row: any) => { const o = { ...row }; for (const k of Object.keys(o)) if (SENSITIVE.test(k)) delete o[k]; return o; });
}

// Insert one row into a REAL project table — only into columns that actually exist, fully parameterized.
export async function insertRow(pool: pg.Pool, projectId: string, table: string, data: Record<string, any>): Promise<boolean> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table)) return false;
  const tables = await listTables(pool, projectId);
  if (!tables.includes(table)) return false;
  const cols = (await columns(pool, schema, table)).filter(col => col in (data || {}) && IDENT.test(col) && col !== 'id' && col !== 'created_at');
  if (!cols.length) return false;
  const vals = cols.map((_, i) => '$' + (i + 1));
  await pool.query(`insert into "${schema}"."${table}" (${cols.map(c => `"${c}"`).join(',')}) values (${vals.join(',')})`,
    cols.map(col => data[col]));
  return true;
}

// INTROSPECTION — the system knows the database: every table's columns/types, real relations, row counts.
// Read straight from the catalog of the project's own schema. Powers the data API, the build agent, and
// the project workspace's "Database" view.
export async function describeSchema(pool: pg.Pool, projectId: string): Promise<{ schema: string; tables: any[] }> {
  const schema = schemaName(projectId);
  const tabs = await listTables(pool, projectId);
  const tables: any[] = [];
  for (const t of tabs) {
    const cols = (await pool.query(
      'select column_name, data_type, is_nullable from information_schema.columns where table_schema=$1 and table_name=$2 order by ordinal_position', [schema, t])).rows;
    const fks = (await pool.query(
      `select kcu.column_name as col, ccu.table_name as ref
       from information_schema.table_constraints tc
       join information_schema.key_column_usage kcu on kcu.constraint_name=tc.constraint_name and kcu.table_schema=tc.table_schema
       join information_schema.constraint_column_usage ccu on ccu.constraint_name=tc.constraint_name and ccu.table_schema=tc.table_schema
       where tc.constraint_type='FOREIGN KEY' and tc.table_schema=$1 and tc.table_name=$2`, [schema, t])).rows;
    let rows = 0; try { rows = Number((await pool.query(`select count(*)::int n from "${schema}"."${t}"`)).rows[0].n); } catch {}
    tables.push({
      table: t, rows,
      columns: cols.map((c: any) => ({ name: c.column_name, type: c.data_type, nullable: c.is_nullable === 'YES' })),
      relations: fks.map((f: any) => ({ column: f.col, references: f.ref })),
    });
  }
  return { schema, tables };
}
